Repository halo-dev/docs, pull requests merged in 2022-11, with the labels that each got.

#106 docs: update documentation for Halo 2.0.0-beta.1
  docs/developer-guide/core/run.md
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  docs/intro.md
Labels: approved, kind/documentation, release-note-none, lgtm

#108 Change mirror frontend URL from https://dl.halo.run to https://download.halo.run
  docs/getting-started/downloads.md
  versioned_docs/version-1.4/getting-started/downloads.md
  versioned_docs/version-1.5/getting-started/downloads.md
  versioned_docs/version-1.6/getting-started/downloads.md
Labels: approved, release-note-none, lgtm

#102 docs: add basic documentation for theme development
  docs/developer-guide/theme/prepare.md
  docs/developer-guide/theme/structure.md
  sidebars.js
Labels: approved, kind/documentation, do-not-merge/release-note-label-needed, lgtm

#111 docs: update documentation for Halo 2.0.0-beta.2
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  docs/intro.md
Labels: approved, kind/documentation, release-note-none, lgtm

#110 docs: refine theme development documentation
  docs/developer-guide/form-schema.md
  docs/developer-guide/theme/code-snippets.md
  docs/developer-guide/theme/config-files.md
  docs/developer-guide/theme/config.md
  docs/developer-guide/theme/finder-apis.md
  docs/developer-guide/theme/finder-apis/category.md
  docs/developer-guide/theme/finder-apis/comment.md
  docs/developer-guide/theme/finder-apis/contributor.md
  docs/developer-guide/theme/finder-apis/menu.md
  docs/developer-guide/theme/finder-apis/plugin.md
  docs/developer-guide/theme/finder-apis/post.md
  docs/developer-guide/theme/finder-apis/single-page.md
  docs/developer-guide/theme/finder-apis/site-stats.md
  docs/developer-guide/theme/finder-apis/tag.md
  docs/developer-guide/theme/finder-apis/theme.md
  docs/developer-guide/theme/global-variable.md
  docs/developer-guide/theme/page-variable.md
  docs/developer-guide/theme/prepare.md
  docs/developer-guide/theme/public-template-tag.md
  docs/developer-guide/theme/settings.md
  docs/developer-guide/theme/static-resources.md
  docs/developer-guide/theme/structure.md
  docs/developer-guide/theme/template-route-mapping.md
  docs/developer-guide/theme/template-tag.md
  docs/developer-guide/theme/template-variables.md
  docs/developer-guide/theme/template-variables/archives.md
  docs/developer-guide/theme/template-variables/categories.md
  docs/developer-guide/theme/template-variables/category.md
  docs/developer-guide/theme/template-variables/index_.md
  docs/developer-guide/theme/template-variables/page.md
  docs/developer-guide/theme/template-variables/post.md
  docs/developer-guide/theme/template-variables/tag.md
  docs/developer-guide/theme/template-variables/tags.md
  docusaurus.config.js
  sidebars.js
  static/img/formkit/formkit-repeater.png
Labels: approved, kind/documentation, release-note-none, lgtm

#116 docs: fix typo
  docs/developer-guide/core/run.md
Labels: approved, release-note-none, lgtm

#117 docs: update documentation for Halo 2.0.0-rc.1
  docs/developer-guide/core/run.md
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  docs/getting-started/prepare.md
  docs/intro.md
Labels: approved, kind/documentation, release-note-none, lgtm

#118 docs: 更新'写在前面'部分适配2.0变化
  docs/getting-started/prepare.md
Labels: approved, release-note-none, lgtm

#119 Adapt lint script in Windows platform
  package.json
Labels: approved, release-note-none, lgtm, kind/improvement

#120 docs: tips for configuring template caching for theme development
  docs/developer-guide/theme/prepare.md
Labels: approved, kind/documentation, release-note-none, lgtm
