Repository halo-dev/docs, pull requests merged in 2022-04, with the labels that each got.

#67 docs: remove tencent developer labs sidebar link
  i18n/zh-Hans/code.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.5.1.json
  sidebars.js
  versioned_sidebars/version-1.5.1-sidebars.json
Labels: approved, kind/documentation, lgtm

#65 docs: add docker-compose upgrade method
  docs/getting-started/install/other/docker-compose.md
  docs/getting-started/upgrade.md
Labels: approved, lgtm

#68 docs: update documentations for Halo 1.5.2
  docs/getting-started/install/docker.md
  docs/getting-started/install/linux.md
  docs/getting-started/install/other/docker-compose.md
  docs/getting-started/install/other/docker-mysql.md
  docs/getting-started/upgrade.md
  docs/intro.md
Labels: approved, kind/documentation

#69 release: create 1.5.2 version
  i18n/zh-Hans/code.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-1.5.2.json
  package.json
  versioned_docs/version-1.5.2/about.md
  versioned_docs/version-1.5.2/contribution/issue.md
  versioned_docs/version-1.5.2/contribution/pr.md
  versioned_docs/version-1.5.2/developer-guide/core/code-style.md
  versioned_docs/version-1.5.2/developer-guide/core/prepare.md
  versioned_docs/version-1.5.2/developer-guide/core/structure.md
  versioned_docs/version-1.5.2/developer-guide/theme/config-files.md
  versioned_docs/version-1.5.2/developer-guide/theme/global-variable.md
  versioned_docs/version-1.5.2/developer-guide/theme/page-variable.md
  versioned_docs/version-1.5.2/developer-guide/theme/prepare.md
  versioned_docs/version-1.5.2/developer-guide/theme/public-template-tag.md
  versioned_docs/version-1.5.2/developer-guide/theme/template-tag.md
  versioned_docs/version-1.5.2/getting-started/config.md
  versioned_docs/version-1.5.2/getting-started/downloads.md
  versioned_docs/version-1.5.2/getting-started/install/docker.md
  versioned_docs/version-1.5.2/getting-started/install/linux.md
  versioned_docs/version-1.5.2/getting-started/install/other/bt-panel.md
  versioned_docs/version-1.5.2/getting-started/install/other/docker-compose.md
  versioned_docs/version-1.5.2/getting-started/install/other/docker-mysql.md
  versioned_docs/version-1.5.2/getting-started/install/other/oneinstack.md
  versioned_docs/version-1.5.2/getting-started/install/other/tencent-cloudbase.md
  versioned_docs/version-1.5.2/getting-started/install/third-party.md
  versioned_docs/version-1.5.2/getting-started/install/windows.md
  versioned_docs/version-1.5.2/getting-started/prepare.md
  versioned_docs/version-1.5.2/getting-started/upgrade.md
  versioned_docs/version-1.5.2/intro.md
  versioned_docs/version-1.5.2/user-guide/backup-migration.md
  versioned_docs/version-1.5.2/user-guide/config.md
  versioned_docs/version-1.5.2/user-guide/faq.md
  versioned_docs/version-1.5.2/user-guide/markdown.md
  versioned_sidebars/version-1.5.2-sidebars.json
  versions.json
Labels: kind/documentation, lgtm

#70 docs: update markdown.md for Halo 1.5.x
  docs/user-guide/markdown.md
  docusaurus.config.js
  package.json
  pnpm-lock.yaml
  versioned_docs/version-1.5.2/user-guide/markdown.md
Labels: approved, kind/documentation, lgtm

#74 docs: improve docker compose documentations
  .markdownlint.json
  docs/getting-started/install/other/docker-compose.md
  versioned_docs/version-1.5.2/getting-started/install/other/docker-compose.md
Labels: approved, kind/documentation, lgtm

#75 Add gitee source button in Tencent cloud deployment
  docs/getting-started/install/other/tencent-cloudbase.md
Labels: approved, lgtm

#77 Refine pr.md to be clearer
  docs/contribution/pr.md
  versioned_docs/version-1.5.2/contribution/pr.md
Labels: approved, kind/documentation, lgtm
