Repository halo-dev/docs, pull requests merged in 2022-12, with the labels that each got.

#124 docs: add user guide and quick start
  .markdownlint.json
  docs/getting-started/first-post.md
  docs/user-guide/attachments.md
  docs/user-guide/common.md
  docs/user-guide/faq.md
  docs/user-guide/pages.md
  docs/user-guide/plugins.md
  docs/user-guide/posts.md
  docs/user-guide/settings.md
  docs/user-guide/themes.md
  docs/user-guide/users.md
  sidebars.js
  static/img/TBD.png
  static/img/first-post.gif
  static/img/user-guide/attachments/attachment-batch-operate.png
  static/img/user-guide/attachments/attachment-group-add.png
  static/img/user-guide/attachments/attachment-group-delete.png
  static/img/user-guide/attachments/attachment-policy-add-local.png
  static/img/user-guide/attachments/attachment-policy-add.png
  static/img/user-guide/attachments/attachment-policy-operate.png
  static/img/user-guide/attachments/attachment-policy.png
  static/img/user-guide/attachments/attachment-upload-multiple.png
  static/img/user-guide/attachments/attachment-upload.png
  static/img/user-guide/common/控制台界面说明.png
  static/img/user-guide/pages/page-about.png
  static/img/user-guide/pages/page-links-edit.png
  static/img/user-guide/pages/page-links.png
  static/img/user-guide/plugins/plugin-install.png
  static/img/user-guide/plugins/plugin-setting.png
  static/img/user-guide/plugins/plugin-switch.png
  static/img/user-guide/posts/category-create.png
  static/img/user-guide/posts/category-move.gif
  static/img/user-guide/posts/post-edit.png
  static/img/user-guide/posts/post-setting.png
  static/img/user-guide/posts/tag-create.png
  static/img/user-guide/posts/tag-list.png
  static/img/user-guide/settings/setting-basic.png
  static/img/user-guide/themes/theme-install-alt.png
  static/img/user-guide/themes/theme-install.png
  static/img/user-guide/themes/theme-preview.png
  static/img/user-guide/themes/theme-setting.png
  static/img/user-guide/themes/theme-uninstall.png
  static/img/user-guide/user-permission.png
  static/img/user-guide/users/role-fork.png
  static/img/user-guide/users/role-management.png
  static/img/user-guide/users/user-operate.png
  static/img/user-guide/users/user-setting.png
Labels: approved, lgtm, release-note

#115 docs: adding documentation for migration from 1.x
  docs/getting-started/migrate-from-1.x.md
  sidebars.js
  static/img/migrate/halo2.0-migrate-plugin.png
Labels: approved, release-note-none, lgtm

#125 docs: update documentation for Halo 2.0.0
  docs/developer-guide/core/run.md
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  docs/getting-started/install/linux.md
  docs/getting-started/install/other/bt-panel.md
  docs/getting-started/install/other/docker-mysql.md
  docs/getting-started/install/other/oneinstack.md
  docs/getting-started/install/other/tencent-cloudbase.md
  docs/getting-started/install/third-party.md
  docs/getting-started/install/windows.md
  docs/getting-started/upgrade.md
  docs/intro.md
  sidebars.js
  static/img/ali-pay.png
  static/img/wechat-pay.png
Labels: approved, kind/documentation, release-note-none, lgtm

#128 docs: update docker-compose.md for PostgreSQL PGUSER env
  docs/getting-started/install/docker-compose.md
Labels: approved, release-note-none, lgtm

#129 docs: add docker installation tips
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  docs/getting-started/prepare.md
  docs/user-guide/faq.md
  versioned_docs/version-2.0/getting-started/install/docker-compose.md
  versioned_docs/version-2.0/getting-started/install/docker.md
  versioned_docs/version-2.0/getting-started/prepare.md
  versioned_docs/version-2.0/user-guide/faq.md
Labels: approved, kind/documentation, release-note-none, lgtm

#130 docs: update tips for migration
  docs/getting-started/migrate-from-1.x.md
  versioned_docs/version-2.0/getting-started/migrate-from-1.x.md
Labels: approved, kind/documentation, release-note-none, lgtm

#134 docs: remove third-party document
  docs/getting-started/install/third-party.md
  sidebars.js
  versioned_docs/version-2.0/getting-started/install/third-party.md
  versioned_sidebars/version-2.0-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#136 feat: improve the quick start section of the introduction
  docs/intro.md
  versioned_docs/version-2.0/intro.md
Labels: approved, kind/documentation, release-note-none, lgtm

#139 docs: improve the developer run guide
  docs/developer-guide/core/run.md
  static/img/developer-run/IntelliJ-IDEA-Profiles-MacOs.png
  static/img/developer-run/IntelliJ-IDEA-Profiles-Win.png
  static/img/developer-run/IntelliJ-IDEA-Profiles.png
  versioned_docs/version-2.0/developer-guide/core/run.md
Labels: approved, release-note-none, lgtm

#142 docs: recover FAQ in sidebar
  sidebars.js
  versioned_sidebars/version-2.0-sidebars.json
Labels: approved, lgtm, release-note

#138 docs: add documentation about compilation
  docs/developer-guide/core/build.md
  docs/developer-guide/core/prepare.md
  docs/developer-guide/core/run.md
  sidebars.js
  versioned_docs/version-2.0/developer-guide/core/build.md
  versioned_docs/version-2.0/developer-guide/core/prepare.md
  versioned_docs/version-2.0/developer-guide/core/run.md
  versioned_sidebars/version-2.0-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#145 docs: add password resetting section in FAQ
  docs/getting-started/first-post.md
  docs/user-guide/common.md
  docs/user-guide/faq.md
  versioned_docs/version-2.0/getting-started/first-post.md
  versioned_docs/version-2.0/user-guide/common.md
  versioned_docs/version-2.0/user-guide/faq.md
Labels: approved, lgtm, release-note

#137 docs: add description of the docker environment variable
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  docs/getting-started/install/slots/docker-env.md
  versioned_docs/version-2.0/getting-started/install/docker-compose.md
  versioned_docs/version-2.0/getting-started/install/docker.md
  versioned_docs/version-2.0/getting-started/install/slots/docker-env.md
Labels: approved, kind/documentation, release-note-none, lgtm

#147 docs: update documentation for pull request contribution
  docs/contribution/pr.md
  versioned_docs/version-2.0/contribution/pr.md
Labels: approved, kind/documentation, release-note-none, lgtm

#152 Fix illustration for uninstalling plugins
  docs/user-guide/plugins.md
  static/img/user-guide/plugins/plugin-uninstall.png
  versioned_docs/version-2.0/user-guide/plugins.md
Labels: approved, lgtm, release-note

#149 docs: add documentation for use with Nginx Proxy Manager
  docs/getting-started/install/other/nginxproxymanager.md
  sidebars.js
  static/img/nginx-proxy-manager/Nginx-Proxy-Manager-1.png
  static/img/nginx-proxy-manager/Nginx-Proxy-Manager-2.png
  static/img/nginx-proxy-manager/Nginx-Proxy-Manager-3.png
  static/img/nginx-proxy-manager/Nginx-Proxy-Manager-4.png
  static/img/nginx-proxy-manager/Nginx-Proxy-Manager-5.png
  static/img/nginx-proxy-manager/Nginx-Proxy-Manager-6.png
  static/img/nginx-proxy-manager/Nginx-Proxy-Manager-7.png
  static/img/nginx-proxy-manager/Nginx-Proxy-Manager-8.png
  versioned_docs/version-2.0/getting-started/install/other/nginxproxymanager.md
  versioned_sidebars/version-2.0-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#155 docs: remove the "Internal members can access" option from the post's usage documentation
  docs/user-guide/posts.md
  versioned_docs/version-2.0/user-guide/posts.md
Labels: approved, release-note-none, lgtm

#159 docs: refine user guide documentation for Halo 2.1.0
  docs/user-guide/plugins.md
  docs/user-guide/posts.md
  docs/user-guide/themes.md
  docs/user-guide/users.md
  static/img/user-guide/plugins/plugin-uninstall.png
  static/img/user-guide/posts/post-edit.png
  static/img/user-guide/themes/theme-install.png
  static/img/user-guide/themes/theme-uninstall.png
Labels: approved, release-note-none, lgtm
