Repository halo-dev/docs, pull requests merged in 2023-06, with the labels that each got.

#224 docs: update form schema link
  docs/developer-guide/form-schema.md
  versioned_docs/version-2.6/developer-guide/form-schema.md
Labels: approved, release-note-none, lgtm

#226 docs: fix typos and word case
  docs/developer-guide/core/run.md
  docs/developer-guide/plugin/examples/todolist.md
  docs/developer-guide/plugin/manifest.md
  docs/developer-guide/plugin/publish.md
  docs/getting-started/install/1panel.md
  docs/user-guide/config.md
  docs/user-guide/markdown.md
  static/img/developer-run/IntelliJ-IDEA-Profiles-macOS.png
  versioned_docs/version-1.4/developer-guide/core/prepare.md
  versioned_docs/version-1.4/user-guide/config.md
  versioned_docs/version-1.5/developer-guide/core/prepare.md
  versioned_docs/version-1.5/user-guide/config.md
  versioned_docs/version-1.5/user-guide/markdown.md
  versioned_docs/version-1.6/developer-guide/core/prepare.md
  versioned_docs/version-1.6/user-guide/config.md
  versioned_docs/version-1.6/user-guide/markdown.md
  versioned_docs/version-2.0/developer-guide/core/run.md
  versioned_docs/version-2.0/user-guide/config.md
  versioned_docs/version-2.0/user-guide/markdown.md
  versioned_docs/version-2.1/developer-guide/core/run.md
  versioned_docs/version-2.1/user-guide/config.md
  versioned_docs/version-2.1/user-guide/markdown.md
  versioned_docs/version-2.2/developer-guide/core/run.md
  versioned_docs/version-2.2/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.2/developer-guide/plugin/manifest.md
  versioned_docs/version-2.2/developer-guide/plugin/publish.md
  versioned_docs/version-2.2/user-guide/config.md
  versioned_docs/version-2.2/user-guide/markdown.md
  versioned_docs/version-2.3/developer-guide/core/run.md
  versioned_docs/version-2.3/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.3/developer-guide/plugin/manifest.md
  versioned_docs/version-2.3/developer-guide/plugin/publish.md
  versioned_docs/version-2.3/getting-started/install/1panel.md
  versioned_docs/version-2.3/user-guide/config.md
  versioned_docs/version-2.3/user-guide/markdown.md
  versioned_docs/version-2.4/developer-guide/core/run.md
  versioned_docs/version-2.4/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.4/developer-guide/plugin/manifest.md
  versioned_docs/version-2.4/developer-guide/plugin/publish.md
  versioned_docs/version-2.4/getting-started/install/1panel.md
  versioned_docs/version-2.4/user-guide/config.md
  versioned_docs/version-2.4/user-guide/markdown.md
  versioned_docs/version-2.5/developer-guide/core/run.md
  versioned_docs/version-2.5/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.5/developer-guide/plugin/manifest.md
  versioned_docs/version-2.5/developer-guide/plugin/publish.md
  versioned_docs/version-2.5/getting-started/install/1panel.md
  versioned_docs/version-2.5/user-guide/config.md
  versioned_docs/version-2.5/user-guide/markdown.md
  versioned_docs/version-2.6/developer-guide/core/run.md
  versioned_docs/version-2.6/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.6/developer-guide/plugin/manifest.md
  versioned_docs/version-2.6/developer-guide/plugin/publish.md
  versioned_docs/version-2.6/getting-started/install/1panel.md
  versioned_docs/version-2.6/user-guide/config.md
  versioned_docs/version-2.6/user-guide/markdown.md
Labels: approved, release-note-none, lgtm, kind/improvement

#227 chore: update site configs
  docusaurus.config.js
  i18n/zh-Hans/code.json
  i18n/zh-Hans/docusaurus-theme-classic/footer.json
  i18n/zh-Hans/docusaurus-theme-classic/navbar.json
Labels: approved, release-note-none, lgtm, kind/improvement

#225 docs: refactor documentations of user guide
  docs/developer-guide/core/code-style.md
  docs/getting-started/first-post.md
  docs/user-guide/attachments.md
  docs/user-guide/common.md
  docs/user-guide/config.md
  docs/user-guide/faq.md
  docs/user-guide/markdown.md
  docs/user-guide/pages.md
  docs/user-guide/plugins.md
  docs/user-guide/posts.md
  docs/user-guide/settings.md
  docs/user-guide/themes.md
  docs/user-guide/users.md
  src/css/custom.css
  static/img/user-guide/attachments/attachment-batch-operate.png
  static/img/user-guide/attachments/attachment-detail.png
  static/img/user-guide/attachments/attachment-group-add.png
  static/img/user-guide/attachments/attachment-move.png
  static/img/user-guide/attachments/attachment-policy-add-local.png
  static/img/user-guide/attachments/attachment-policy-add.png
  static/img/user-guide/attachments/attachment-policy-operate.png
  static/img/user-guide/attachments/attachment-upload.png
  static/img/user-guide/common/控制台界面说明.png
  static/img/user-guide/pages/page-about.png
  static/img/user-guide/plugins/plugin-install.png
  static/img/user-guide/plugins/plugin-setting.png
  static/img/user-guide/plugins/plugin-switch.png
  static/img/user-guide/plugins/plugin-uninstall.png
  static/img/user-guide/posts/category-create.png
  static/img/user-guide/posts/category-move.gif
  static/img/user-guide/posts/post-edit.png
  static/img/user-guide/posts/post-setting.png
  static/img/user-guide/posts/tag-create.png
  static/img/user-guide/posts/tag-list.png
  static/img/user-guide/settings/setting-basic.png
  static/img/user-guide/themes/theme-install.png
  static/img/user-guide/themes/theme-setting.png
  static/img/user-guide/themes/theme-uninstall.png
  static/img/user-guide/users/auth-providers-entry.png
  static/img/user-guide/users/auth-providers.png
  static/img/user-guide/users/role-fork.png
  static/img/user-guide/users/role-management.png
  static/img/user-guide/users/user-operate.png
  static/img/user-guide/users/user-setting.png
  versioned_docs/version-2.6/developer-guide/core/code-style.md
  versioned_docs/version-2.6/getting-started/first-post.md
  versioned_docs/version-2.6/user-guide/attachments.md
  versioned_docs/version-2.6/user-guide/common.md
  versioned_docs/version-2.6/user-guide/config.md
  versioned_docs/version-2.6/user-guide/faq.md
  versioned_docs/version-2.6/user-guide/pages.md
  versioned_docs/version-2.6/user-guide/plugins.md
  versioned_docs/version-2.6/user-guide/posts.md
  versioned_docs/version-2.6/user-guide/settings.md
  versioned_docs/version-2.6/user-guide/themes.md
  versioned_docs/version-2.6/user-guide/users.md
Labels: approved, kind/documentation, release-note-none, lgtm

#228 chore: bump docusaurus version to 2.4
  package.json
  pnpm-lock.yaml
Labels: approved, release-note-none, lgtm

#229 docs: improve documentation of 1Panel
  docs/getting-started/install/1panel.md
  static/img/install/1panel/1panel.png
  static/img/install/1panel/app-store-halo.png
  static/img/install/1panel/halo-console.png
  static/img/install/1panel/halo-status.png
  static/img/install/1panel/install-halo.png
  static/img/install/1panel/new-site.png
  static/img/install/1panel/openresty-mysql.png
  static/img/install/1panel/site.png
  versioned_docs/version-2.6/getting-started/install/1panel.md
Labels: approved, kind/documentation, release-note-none, lgtm

#232 docs: refine repeater props
  docs/developer-guide/form-schema.md
  versioned_docs/version-2.6/developer-guide/form-schema.md
Labels: approved, kind/documentation, release-note-none, lgtm

#231 docs: fix broken link in backup-migration.md
  versioned_docs/version-1.4/user-guide/backup-migration.md
  versioned_docs/version-1.5/user-guide/backup-migration.md
  versioned_docs/version-1.6/user-guide/backup-migration.md
Labels: release-note-none, lgtm

#230 docs: fix headings of nginxproxymanager.md
  docs/getting-started/install/other/nginxproxymanager.md
  sidebars.js
  versioned_docs/version-2.0/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.1/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.2/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.3/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.4/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.5/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.6/getting-started/install/other/nginxproxymanager.md
  versioned_sidebars/version-2.6-sidebars.json
Labels: kind/documentation, release-note-none, lgtm

#233 docs: 增加 Helm 部署文档
  docs/getting-started/install/helm.md
  sidebars.js
  versioned_docs/version-2.6/getting-started/install/helm.md
  versioned_sidebars/version-2.6-sidebars.json
Labels: approved, do-not-merge/release-note-label-needed, lgtm
