Repository halo-dev/docs, pull requests merged in 2023-02, with the labels that each got.

#175 docs: add lastModifyTime field description for post and singlePage related vo
  docs/developer-guide/theme/vo/ListedPostVo.md
  docs/developer-guide/theme/vo/ListedSinglePageVo.md
  docs/developer-guide/theme/vo/PostVo.md
  docs/developer-guide/theme/vo/SinglePageVo.md
  versioned_docs/version-2.2/developer-guide/theme/vo/ListedPostVo.md
  versioned_docs/version-2.2/developer-guide/theme/vo/ListedSinglePageVo.md
  versioned_docs/version-2.2/developer-guide/theme/vo/PostVo.md
  versioned_docs/version-2.2/developer-guide/theme/vo/SinglePageVo.md
Labels: approved, kind/documentation, release-note-none, lgtm

#178 docs: add tips of console proxy
  docs/developer-guide/core/run.md
  versioned_docs/version-2.0/developer-guide/core/run.md
  versioned_docs/version-2.1/developer-guide/core/run.md
  versioned_docs/version-2.2/developer-guide/core/run.md
Labels: approved, kind/documentation, release-note-none, lgtm

#177 docs: add documentation for update docker image to upgrade halo
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  versioned_docs/version-2.0/getting-started/install/docker-compose.md
  versioned_docs/version-2.0/getting-started/install/docker.md
  versioned_docs/version-2.1/getting-started/install/docker-compose.md
  versioned_docs/version-2.1/getting-started/install/docker.md
  versioned_docs/version-2.2/getting-started/install/docker-compose.md
  versioned_docs/version-2.2/getting-started/install/docker.md
Labels: approved, kind/documentation, release-note-none, lgtm

#183 docs: remove version tips
  docs/getting-started/prepare.md
  versioned_docs/version-2.0/getting-started/prepare.md
  versioned_docs/version-2.1/getting-started/prepare.md
  versioned_docs/version-2.2/getting-started/prepare.md
Labels: approved, kind/documentation, release-note-none, lgtm

#180 docs: add documentation for template engine global variables
  docs/developer-guide/theme/global-variables.md
  docs/developer-guide/theme/vo/SiteSettingVo.md
  docs/developer-guide/theme/vo/ThemeVo.md
  sidebars.js
  versioned_docs/version-2.0/developer-guide/theme/global-variables.md
  versioned_docs/version-2.0/developer-guide/theme/vo/SiteSettingVo.md
  versioned_docs/version-2.0/developer-guide/theme/vo/ThemeVo.md
  versioned_docs/version-2.1/developer-guide/theme/global-variables.md
  versioned_docs/version-2.1/developer-guide/theme/vo/SiteSettingVo.md
  versioned_docs/version-2.1/developer-guide/theme/vo/ThemeVo.md
  versioned_docs/version-2.2/developer-guide/theme/global-variables.md
  versioned_docs/version-2.2/developer-guide/theme/vo/SiteSettingVo.md
  versioned_docs/version-2.2/developer-guide/theme/vo/ThemeVo.md
  versioned_sidebars/version-2.0-sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-2.2-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#184 docs: bump docusaurus version to 2.3.0
  package.json
  pnpm-lock.yaml
Labels: approved, release-note-none, lgtm, kind/improvement

#179 docs: add documentation for custom template tag
  docs/developer-guide/theme/template-tag.md
  sidebars.js
  versioned_docs/version-2.0/developer-guide/theme/template-tag.md
  versioned_docs/version-2.1/developer-guide/theme/template-tag.md
  versioned_docs/version-2.2/developer-guide/theme/template-tag.md
  versioned_sidebars/version-2.0-sidebars.json
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-2.2-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#172 docs: add documentation of traefik proxy
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/other/traefik.md
  sidebars.js
  versioned_docs/version-2.1/getting-started/install/docker-compose.md
  versioned_docs/version-2.1/getting-started/install/other/traefik.md
  versioned_docs/version-2.2/getting-started/install/docker-compose.md
  versioned_docs/version-2.2/getting-started/install/other/traefik.md
  versioned_sidebars/version-2.1-sidebars.json
  versioned_sidebars/version-2.2-sidebars.json
Labels: approved, release-note-none, lgtm

#186 fix: nginx link error in docker-compose page
  docs/getting-started/install/docker-compose.md
  versioned_docs/version-2.1/getting-started/install/docker-compose.md
  versioned_docs/version-2.2/getting-started/install/docker-compose.md
Labels: approved, release-note-none, lgtm

#123 feat: add plugin development docs
  docs/developer-guide/plugin/api-reference/extension-client.md
  docs/developer-guide/plugin/api-reference/extension.md
  docs/developer-guide/plugin/api-reference/reverseproxy.md
  docs/developer-guide/plugin/api-reference/role-template.md
  docs/developer-guide/plugin/examples/todolist.md
  docs/developer-guide/plugin/hello-world.md
  docs/developer-guide/plugin/introduction.md
  docs/developer-guide/plugin/lifecycle.md
  docs/developer-guide/plugin/manifest.md
  docs/developer-guide/plugin/object-management.md
  docs/developer-guide/plugin/prepare.md
  docs/developer-guide/plugin/publish.md
  docs/developer-guide/plugin/runtime-mode.md
  docs/developer-guide/plugin/structure.md
  sidebars.js
  static/img/create-repository-for-hello-world-plugin.png
  static/img/halo-plugin-hello-world-todo-swagger-api.png
  static/img/plugin-hello-world.png
  static/img/todo-logo-check-48.png
  static/img/todo-ui.png
  static/img/todolist-in-list.png
  static/img/unplugin-icons-example.png
  versioned_docs/version-2.2/developer-guide/plugin/api-reference/extension-client.md
  versioned_docs/version-2.2/developer-guide/plugin/api-reference/extension.md
  versioned_docs/version-2.2/developer-guide/plugin/api-reference/reverseproxy.md
  versioned_docs/version-2.2/developer-guide/plugin/api-reference/role-template.md
  versioned_docs/version-2.2/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.2/developer-guide/plugin/hello-world.md
  versioned_docs/version-2.2/developer-guide/plugin/introduction.md
  versioned_docs/version-2.2/developer-guide/plugin/lifecycle.md
  versioned_docs/version-2.2/developer-guide/plugin/manifest.md
  versioned_docs/version-2.2/developer-guide/plugin/object-management.md
  versioned_docs/version-2.2/developer-guide/plugin/prepare.md
  versioned_docs/version-2.2/developer-guide/plugin/publish.md
  versioned_docs/version-2.2/developer-guide/plugin/runtime-mode.md
  versioned_docs/version-2.2/developer-guide/plugin/structure.md
  versioned_sidebars/version-2.2-sidebars.json
Labels: approved, release-note-none, lgtm

#189 docs: add healthcheck for halo in compose
  docs/getting-started/install/docker-compose.md
  versioned_docs/version-2.2/getting-started/install/docker-compose.md
Labels: approved, lgtm, release-note

#192 docs: add a tip for default admin username and password for development environment
  docs/developer-guide/core/run.md
  versioned_docs/version-2.0/developer-guide/core/run.md
  versioned_docs/version-2.1/developer-guide/core/run.md
  versioned_docs/version-2.2/developer-guide/core/run.md
Labels: approved, kind/documentation, release-note-none, lgtm
