Repository halo-dev/docs, pull requests merged in 2023-10, with the labels that each got.

#263 docs: update ContributorVo (halo-dev/halo#4705)
  docs/developer-guide/theme/vo/ContributorVo.md
Labels: approved, lgtm, release-note

#261 docs: add security notice for oneinstack
  docs/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.0/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.1/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.10/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.2/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.3/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.4/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.5/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.6/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.7/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.8/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.9/getting-started/install/other/oneinstack.md
Labels: approved, kind/documentation, release-note-none, lgtm

#265 docs: add sponsor page
  docs/contribution/sponsor.md
  docs/getting-started/prepare.md
  sidebars.js
  versioned_docs/version-2.10/contribution/sponsor.md
  versioned_docs/version-2.10/getting-started/prepare.md
  versioned_sidebars/version-2.10-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#266 fix: broken links
  docs/developer-guide/core/build.md
  docs/developer-guide/plugin/examples/todolist.md
  docs/user-guide/backup-migration.md
  docs/user-guide/markdown.md
  docusaurus.config.js
  versioned_docs/version-1.4/getting-started/install/other/bt-panel.md
  versioned_docs/version-1.4/getting-started/install/other/oneinstack.md
  versioned_docs/version-1.5/getting-started/install/other/bt-panel.md
  versioned_docs/version-1.5/getting-started/install/other/oneinstack.md
  versioned_docs/version-1.6/getting-started/install/other/bt-panel.md
  versioned_docs/version-1.6/getting-started/install/other/oneinstack.md
  versioned_docs/version-2.0/developer-guide/core/build.md
  versioned_docs/version-2.0/user-guide/backup-migration.md
  versioned_docs/version-2.1/developer-guide/core/build.md
  versioned_docs/version-2.1/user-guide/backup-migration.md
  versioned_docs/version-2.1/user-guide/markdown.md
  versioned_docs/version-2.10/developer-guide/core/build.md
  versioned_docs/version-2.10/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.10/user-guide/backup-migration.md
  versioned_docs/version-2.10/user-guide/markdown.md
  versioned_docs/version-2.2/developer-guide/core/build.md
  versioned_docs/version-2.2/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.2/user-guide/backup-migration.md
  versioned_docs/version-2.2/user-guide/markdown.md
  versioned_docs/version-2.3/developer-guide/core/build.md
  versioned_docs/version-2.3/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.3/user-guide/backup-migration.md
  versioned_docs/version-2.3/user-guide/markdown.md
  versioned_docs/version-2.4/developer-guide/core/build.md
  versioned_docs/version-2.4/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.4/user-guide/backup-migration.md
  versioned_docs/version-2.4/user-guide/markdown.md
  versioned_docs/version-2.5/developer-guide/core/build.md
  versioned_docs/version-2.5/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.5/user-guide/backup-migration.md
  versioned_docs/version-2.5/user-guide/markdown.md
  versioned_docs/version-2.6/developer-guide/core/build.md
  versioned_docs/version-2.6/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.6/user-guide/backup-migration.md
  versioned_docs/version-2.6/user-guide/markdown.md
  versioned_docs/version-2.7/developer-guide/core/build.md
  versioned_docs/version-2.7/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.7/user-guide/backup-migration.md
  versioned_docs/version-2.7/user-guide/markdown.md
  versioned_docs/version-2.8/developer-guide/core/build.md
  versioned_docs/version-2.8/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.8/user-guide/backup-migration.md
  versioned_docs/version-2.8/user-guide/markdown.md
  versioned_docs/version-2.9/developer-guide/core/build.md
  versioned_docs/version-2.9/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.9/user-guide/backup-migration.md
  versioned_docs/version-2.9/user-guide/markdown.md
Labels: approved, kind/documentation, release-note-none, lgtm

#267 chore: add ssh deploy step
  .github/workflows/node.js.yml
Labels: approved, release-note-none, lgtm, kind/improvement

#268 chore: zip dist files before ssh deploy
  .github/workflows/node.js.yml
Labels: approved, release-note-none, lgtm, kind/improvement

#271 docs: improve documentations of plugin development
  docs/developer-guide/plugin/api-reference/extension.md
  docs/developer-guide/plugin/api-reference/reverseproxy.md
  docs/developer-guide/plugin/api-reference/role-template.md
  docs/developer-guide/plugin/examples/todolist.md
  docs/developer-guide/plugin/hello-world.md
  docs/developer-guide/plugin/introduction.md
  docs/developer-guide/plugin/lifecycle.md
  docs/developer-guide/plugin/manifest.md
  docs/developer-guide/plugin/prepare.md
  docs/developer-guide/plugin/publish.md
  docs/developer-guide/plugin/runtime-mode.md
  docs/developer-guide/plugin/structure.md
  versioned_docs/version-2.10/developer-guide/plugin/api-reference/extension.md
  versioned_docs/version-2.10/developer-guide/plugin/api-reference/reverseproxy.md
  versioned_docs/version-2.10/developer-guide/plugin/api-reference/role-template.md
  versioned_docs/version-2.10/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.10/developer-guide/plugin/hello-world.md
  versioned_docs/version-2.10/developer-guide/plugin/introduction.md
  versioned_docs/version-2.10/developer-guide/plugin/lifecycle.md
  versioned_docs/version-2.10/developer-guide/plugin/manifest.md
  versioned_docs/version-2.10/developer-guide/plugin/prepare.md
  versioned_docs/version-2.10/developer-guide/plugin/publish.md
  versioned_docs/version-2.10/developer-guide/plugin/runtime-mode.md
  versioned_docs/version-2.10/developer-guide/plugin/structure.md
  versioned_docs/version-2.2/developer-guide/plugin/publish.md
  versioned_docs/version-2.3/developer-guide/plugin/publish.md
  versioned_docs/version-2.4/developer-guide/plugin/publish.md
  versioned_docs/version-2.5/developer-guide/plugin/publish.md
  versioned_docs/version-2.6/developer-guide/plugin/publish.md
  versioned_docs/version-2.7/developer-guide/plugin/publish.md
  versioned_docs/version-2.8/developer-guide/plugin/publish.md
  versioned_docs/version-2.9/developer-guide/plugin/publish.md
Labels: approved, kind/documentation, release-note-none, lgtm

#272 docs: improve documentations
  docs/developer-guide/core/build.md
  versioned_docs/version-2.10/developer-guide/core/build.md
Labels: approved, kind/documentation, release-note-none, lgtm

#273 docs: improve build step in plugin document
  docs/developer-guide/plugin/hello-world.md
  versioned_docs/version-2.10/developer-guide/plugin/hello-world.md
Labels: approved, kind/documentation, release-note-none, lgtm
