Repository halo-dev/docs, pull requests merged in 2023-09, with the labels that each got.

#244 docs: update the instructions for the initial administrator in the deployment document
  docs/getting-started/first-post.md
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  docs/getting-started/install/other/traefik.md
  docs/getting-started/install/slots/docker-args.md
Labels: approved, kind/documentation, release-note-none

#249 Update MySQL to 8.1.0 to prevent mysql_native_password warning
  docs/getting-started/install/docker-compose.md
Labels: approved, release-note-none, lgtm

#250 feat: add image zoom feature
  docusaurus.config.js
  package.json
  pnpm-lock.yaml
  src/css/custom.css
Labels: approved, release-note-none, lgtm

#251 Remove useless deploy step
  .github/workflows/node.js.yml
Labels: approved, release-note-none, lgtm, kind/cleanup

#252 fix: menu api example in theme dev docs
  docs/developer-guide/theme/annotations.md
  docs/developer-guide/theme/finder-apis/menu.md
  versioned_docs/version-2.0/developer-guide/theme/finder-apis/menu.md
  versioned_docs/version-2.1/developer-guide/theme/annotations.md
  versioned_docs/version-2.1/developer-guide/theme/finder-apis/menu.md
  versioned_docs/version-2.2/developer-guide/theme/annotations.md
  versioned_docs/version-2.2/developer-guide/theme/finder-apis/menu.md
  versioned_docs/version-2.3/developer-guide/theme/annotations.md
  versioned_docs/version-2.3/developer-guide/theme/finder-apis/menu.md
  versioned_docs/version-2.4/developer-guide/theme/annotations.md
  versioned_docs/version-2.4/developer-guide/theme/finder-apis/menu.md
  versioned_docs/version-2.5/developer-guide/theme/annotations.md
  versioned_docs/version-2.5/developer-guide/theme/finder-apis/menu.md
  versioned_docs/version-2.6/developer-guide/theme/annotations.md
  versioned_docs/version-2.6/developer-guide/theme/finder-apis/menu.md
  versioned_docs/version-2.7/developer-guide/theme/annotations.md
  versioned_docs/version-2.7/developer-guide/theme/finder-apis/menu.md
  versioned_docs/version-2.8/developer-guide/theme/annotations.md
  versioned_docs/version-2.8/developer-guide/theme/finder-apis/menu.md
Labels: approved, release-note-none, lgtm

#254 fix: typos in plugin docs
  docs/user-guide/plugins.md
  versioned_docs/version-2.0/user-guide/plugins.md
  versioned_docs/version-2.1/user-guide/plugins.md
  versioned_docs/version-2.2/user-guide/plugins.md
  versioned_docs/version-2.3/user-guide/plugins.md
  versioned_docs/version-2.4/user-guide/plugins.md
  versioned_docs/version-2.5/user-guide/plugins.md
  versioned_docs/version-2.6/user-guide/plugins.md
  versioned_docs/version-2.7/user-guide/plugins.md
  versioned_docs/version-2.8/user-guide/plugins.md
  versioned_docs/version-2.9/user-guide/plugins.md
Labels: approved, do-not-merge/release-note-label-needed, lgtm

#257 docs: lock postgres version in docker compose example
  docs/getting-started/install/docker-compose.md
  versioned_docs/version-2.0/getting-started/install/docker-compose.md
  versioned_docs/version-2.1/getting-started/install/docker-compose.md
  versioned_docs/version-2.2/getting-started/install/docker-compose.md
  versioned_docs/version-2.3/getting-started/install/docker-compose.md
  versioned_docs/version-2.4/getting-started/install/docker-compose.md
  versioned_docs/version-2.5/getting-started/install/docker-compose.md
  versioned_docs/version-2.6/getting-started/install/docker-compose.md
  versioned_docs/version-2.7/getting-started/install/docker-compose.md
  versioned_docs/version-2.8/getting-started/install/docker-compose.md
  versioned_docs/version-2.9/getting-started/install/docker-compose.md
Labels: approved, kind/documentation, release-note-none, lgtm

#260 fix: example code in menu finder api
  versioned_docs/version-2.9/developer-guide/theme/annotations.md
Labels: approved, lgtm, release-note

#256 docs: add halo on podman
  docs/getting-started/install/podman.md
  sidebars.js
  versioned_docs/version-2.9/getting-started/install/podman.md
  versioned_sidebars/version-2.9-sidebars.json
Labels: approved, release-note-none, lgtm

#258 Change mount dir of Halo container to ./halo2
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/other/traefik.md
Labels: approved, lgtm, release-note
