Repository halo-dev/docs, pull requests merged in 2024-09, with the labels that each got.

#405 docs: add image optimization documentation for theme development
  docs/developer-guide/theme/image-optimization.md
  sidebars.js
Labels: approved, kind/documentation, release-note-none, lgtm

#410 docs: supplement formkit select document
  docs/developer-guide/form-schema.md
  versioned_docs/version-2.19/developer-guide/form-schema.md
Labels: approved, release-note-none, lgtm

#411 docs: add docs for unified parameter list method of post finder
  docs/developer-guide/theme/finder-apis/post.md
  versioned_docs/version-2.19/developer-guide/theme/finder-apis/post.md
Labels: approved, release-note-none, lgtm

#412 docs: add documentation for RESTful API usage
  docs/developer-guide/plugin/api-reference/ui/api-request.md
  docs/developer-guide/plugin/introduction.md
  docs/developer-guide/restful-api/api-client.md
  docs/developer-guide/restful-api/introduction.md
  docs/user-guide/user-center.md
  i18n/zh-Hans/code.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
  i18n/zh-Hans/docusaurus-plugin-content-docs/version-2.19.json
  sidebars.js
  static/img/developer-guide/rest-api/swagger-ui-overview.png
  versioned_docs/version-2.17/developer-guide/plugin/api-reference/ui/api-request.md
  versioned_docs/version-2.18/developer-guide/plugin/api-reference/ui/api-request.md
  versioned_docs/version-2.19/developer-guide/plugin/api-reference/ui/api-request.md
  versioned_docs/version-2.19/developer-guide/plugin/introduction.md
  versioned_docs/version-2.19/developer-guide/restful-api/api-client.md
  versioned_docs/version-2.19/developer-guide/restful-api/introduction.md
  versioned_sidebars/version-2.19-sidebars.json
Labels: approved, release-note-none, lgtm

#416 docs: add documentation for menu select form item
  docs/developer-guide/form-schema.md
Labels: approved, kind/documentation, release-note-none, lgtm

#415 docs: add documentation for offline activation of paid apps in the app store
  docs/user-guide/app-store.md
  static/img/user-guide/app-store/app-store-license-generate-license-1.png
  static/img/user-guide/app-store/app-store-license-generate-license-2.png
  static/img/user-guide/app-store/app-store-license-generate-license-3.png
  static/img/user-guide/app-store/app-store-license-offline-option.png
  static/img/user-guide/app-store/app-store-license-offline.png
  versioned_docs/version-2.19/user-guide/app-store.md
Labels: approved, kind/documentation, release-note-none, lgtm

#409 docs: add explanation for formkit select fieldSelectorKey property
  docs/developer-guide/form-schema.md
  versioned_docs/version-2.19/developer-guide/form-schema.md
Labels: approved, release-note-none, lgtm

#425 docs: add alibaba-cloud-computenest.md
  docs/getting-started/install/cloud/alibaba-cloud-computenest.md
  sidebars.js
  static/img/install/alibab-cloud-computenest/deploy_1.jpg
  static/img/install/alibab-cloud-computenest/deploy_2.jpg
  static/img/install/alibab-cloud-computenest/halo-setup.jpg
  versioned_docs/version-2.19/getting-started/install/cloud/alibaba-cloud-computenest.md
  versioned_sidebars/version-2.19-sidebars.json
Labels: approved, do-not-merge/release-note-label-needed, lgtm

#420 docs: refine backup tips
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  docs/getting-started/install/jar-file.md
  docs/getting-started/install/podman.md
  versioned_docs/version-2.19/getting-started/install/docker-compose.md
  versioned_docs/version-2.19/getting-started/install/docker.md
  versioned_docs/version-2.19/getting-started/install/jar-file.md
  versioned_docs/version-2.19/getting-started/install/podman.md
Labels: approved, kind/documentation, release-note-none, lgtm

#426 docs: update alibaba-cloud-computenest deploy url
  docs/getting-started/install/cloud/alibaba-cloud-computenest.md
  versioned_docs/version-2.19/getting-started/install/cloud/alibaba-cloud-computenest.md
Labels: approved, release-note-none, lgtm
