Repository halo-dev/docs, pull requests merged in 2024-10, with the labels that each got.

#432 docs: update screenshots for version 2.20
  docs/getting-started/first-post.md
  docs/getting-started/setup.md
  static/img/setup/setup-2.20.png
  versioned_docs/version-2.20/getting-started/first-post.md
  versioned_docs/version-2.20/getting-started/setup.md
Labels: approved, kind/documentation, release-note-none, lgtm

#433 docs: update halo official website url
  docs/developer-guide/core/code-style.md
  docs/developer-guide/plugin/examples/todolist.md
  docs/getting-started/migrate-from-1.x.md
  docs/intro.md
  docs/user-guide/attachments.md
  docs/user-guide/common.md
  docs/user-guide/posts.md
  docs/user-guide/users.md
  docusaurus.config.js
  versioned_docs/version-2.16/developer-guide/core/code-style.md
  versioned_docs/version-2.16/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.16/getting-started/migrate-from-1.x.md
  versioned_docs/version-2.16/intro.md
  versioned_docs/version-2.16/user-guide/attachments.md
  versioned_docs/version-2.16/user-guide/common.md
  versioned_docs/version-2.16/user-guide/posts.md
  versioned_docs/version-2.16/user-guide/users.md
  versioned_docs/version-2.17/developer-guide/core/code-style.md
  versioned_docs/version-2.17/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.17/getting-started/migrate-from-1.x.md
  versioned_docs/version-2.17/intro.md
  versioned_docs/version-2.17/user-guide/attachments.md
  versioned_docs/version-2.17/user-guide/common.md
  versioned_docs/version-2.17/user-guide/posts.md
  versioned_docs/version-2.17/user-guide/users.md
  versioned_docs/version-2.18/developer-guide/core/code-style.md
  versioned_docs/version-2.18/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.18/getting-started/migrate-from-1.x.md
  versioned_docs/version-2.18/intro.md
  versioned_docs/version-2.18/user-guide/attachments.md
  versioned_docs/version-2.18/user-guide/common.md
  versioned_docs/version-2.18/user-guide/posts.md
  versioned_docs/version-2.18/user-guide/users.md
  versioned_docs/version-2.19/developer-guide/core/code-style.md
  versioned_docs/version-2.19/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.19/getting-started/migrate-from-1.x.md
  versioned_docs/version-2.19/intro.md
  versioned_docs/version-2.19/user-guide/attachments.md
  versioned_docs/version-2.19/user-guide/common.md
  versioned_docs/version-2.19/user-guide/posts.md
  versioned_docs/version-2.19/user-guide/users.md
  versioned_docs/version-2.20/developer-guide/core/code-style.md
  versioned_docs/version-2.20/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.20/getting-started/migrate-from-1.x.md
  versioned_docs/version-2.20/intro.md
  versioned_docs/version-2.20/user-guide/attachments.md
  versioned_docs/version-2.20/user-guide/common.md
  versioned_docs/version-2.20/user-guide/posts.md
  versioned_docs/version-2.20/user-guide/users.md
Labels: approved, release-note-none, lgtm

#434 docs: add devtools upgrade guide for 0.2.0
  docs/developer-guide/plugin/basics/devtools.md
  versioned_docs/version-2.20/developer-guide/plugin/basics/devtools.md
Labels: approved, release-note-none, lgtm

#438 docs: add Halo configuration documentation
  .vscode/settings.json
  docs/getting-started/install/config.md
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  docs/getting-started/install/jar-file.md
  docs/getting-started/install/offline.md
  docs/getting-started/install/podman.md
  sidebars.js
  versioned_docs/version-2.20/getting-started/install/config.md
  versioned_docs/version-2.20/getting-started/install/docker-compose.md
  versioned_docs/version-2.20/getting-started/install/docker.md
  versioned_docs/version-2.20/getting-started/install/jar-file.md
  versioned_docs/version-2.20/getting-started/install/offline.md
  versioned_docs/version-2.20/getting-started/install/podman.md
  versioned_sidebars/version-2.20-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#440 docs: update basic authentication documentation
  docs/developer-guide/restful-api/introduction.md
  versioned_docs/version-2.20/developer-guide/restful-api/introduction.md
Labels: approved, kind/documentation, release-note-none, lgtm

#442 docs: add JVM_OPTS environment documentation
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  versioned_docs/version-2.20/getting-started/install/docker-compose.md
  versioned_docs/version-2.20/getting-started/install/docker.md
Labels: approved, kind/documentation, release-note-none, lgtm

#441 docs: update intro documentation
  docs/intro.md
  versioned_docs/version-2.20/intro.md
Labels: approved, kind/documentation, release-note-none, lgtm

#445 chore: move framework doc file to core developer dir
  docs/developer-guide/core/framework.md
  docs/developer-guide/plugin/api-reference/server/extension.md
  docs/developer-guide/plugin/api-reference/server/reconciler.md
  docs/developer-guide/plugin/prepare.md
  docs/developer-guide/plugin/security/role-template.md
  sidebars.js
  versioned_docs/version-2.20/developer-guide/core/framework.md
  versioned_docs/version-2.20/developer-guide/plugin/api-reference/server/extension.md
  versioned_docs/version-2.20/developer-guide/plugin/api-reference/server/reconciler.md
  versioned_docs/version-2.20/developer-guide/plugin/prepare.md
  versioned_docs/version-2.20/developer-guide/plugin/security/role-template.md
  versioned_sidebars/version-2.20-sidebars.json
Labels: approved, release-note-none, lgtm

#447 refactor: update plugin structure doc
  docs/developer-guide/plugin/basics/structure.md
  versioned_docs/version-2.20/developer-guide/plugin/basics/structure.md
Labels: approved, release-note-none, lgtm

#448 refactor: update plugin manifest doc
  docs/developer-guide/plugin/basics/manifest.md
  versioned_docs/version-2.20/developer-guide/plugin/basics/manifest.md
Labels: approved, release-note-none, lgtm

#446 docs: update devtools documents
  docs/developer-guide/plugin/basics/devtools.md
  versioned_docs/version-2.20/developer-guide/plugin/basics/devtools.md
Labels: approved, release-note-none, lgtm

#449 docs: add database creation tips
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/jar-file.md
  docusaurus.config.js
  versioned_docs/version-2.20/getting-started/install/docker-compose.md
  versioned_docs/version-2.20/getting-started/install/jar-file.md
Labels: approved, release-note-none, lgtm

#450 docs: restructure theme development documentation
  docs/developer-guide/theme/config.md
  docs/developer-guide/theme/structure.md
  docs/developer-guide/theme/template-variables.md
  docs/developer-guide/theme/template-variables/archives.md
  docs/developer-guide/theme/template-variables/author.md
  docs/developer-guide/theme/template-variables/categories.md
  docs/developer-guide/theme/template-variables/category.md
  docs/developer-guide/theme/template-variables/index_.md
  docs/developer-guide/theme/template-variables/page.md
  docs/developer-guide/theme/template-variables/post.md
  docs/developer-guide/theme/template-variables/tag.md
  docs/developer-guide/theme/template-variables/tags.md
  docs/developer-guide/theme/vo/_ThemeVo.md
  docusaurus.config.js
  sidebars.js
  versioned_docs/version-2.20/developer-guide/theme/config.md
  versioned_docs/version-2.20/developer-guide/theme/structure.md
  versioned_docs/version-2.20/developer-guide/theme/template-variables.md
  versioned_docs/version-2.20/developer-guide/theme/template-variables/archives.md
  versioned_docs/version-2.20/developer-guide/theme/template-variables/author.md
  versioned_docs/version-2.20/developer-guide/theme/template-variables/categories.md
  versioned_docs/version-2.20/developer-guide/theme/template-variables/category.md
  versioned_docs/version-2.20/developer-guide/theme/template-variables/index_.md
  versioned_docs/version-2.20/developer-guide/theme/template-variables/page.md
  versioned_docs/version-2.20/developer-guide/theme/template-variables/post.md
  versioned_docs/version-2.20/developer-guide/theme/template-variables/tag.md
  versioned_docs/version-2.20/developer-guide/theme/template-variables/tags.md
  versioned_docs/version-2.20/developer-guide/theme/vo/_ThemeVo.md
  versioned_sidebars/version-2.20-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#451 docs: add docs for using shared objects within the plugin
  docs/developer-guide/plugin/basics/server/object-management.md
  static/img/developer-guide/plugin/basic/server/post-content-version-generation.png
  versioned_docs/version-2.20/developer-guide/plugin/basics/server/object-management.md
Labels: approved, release-note-none, lgtm

#452 docs: add custom login-related pages documentation
  docs/developer-guide/theme/template-variables/auth.md
  sidebars.js
  static/img/developer-guide/theme/custom-login-layout.png
  static/img/developer-guide/theme/custom-signup-layout.png
  versioned_docs/version-2.20/developer-guide/theme/template-variables/auth.md
  versioned_sidebars/version-2.20-sidebars.json
Labels: approved, kind/documentation, lgtm, release-note

#453 docs: add menu management documentation
  docs/user-guide/menus.md
  sidebars.js
  static/img/user-guide/menus/create-menu-item-2.png
  static/img/user-guide/menus/create-menu-item.png
  static/img/user-guide/menus/create-menu.png
  static/img/user-guide/menus/menu-item-operation.png
  static/img/user-guide/menus/menu-operation.png
  static/img/user-guide/menus/menus.png
  static/img/user-guide/menus/sort.gif
  versioned_docs/version-2.16/user-guide/menus.md
  versioned_docs/version-2.17/user-guide/menus.md
  versioned_docs/version-2.18/user-guide/menus.md
  versioned_docs/version-2.19/user-guide/menus.md
  versioned_docs/version-2.20/user-guide/menus.md
  versioned_sidebars/version-2.16-sidebars.json
  versioned_sidebars/version-2.17-sidebars.json
  versioned_sidebars/version-2.18-sidebars.json
  versioned_sidebars/version-2.19-sidebars.json
  versioned_sidebars/version-2.20-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#454 docs: add documentation for extension point settings
  docs/user-guide/plugins.md
  static/img/user-guide/plugins/extension-point-settings-entry.png
  static/img/user-guide/plugins/extension-point-settings.png
  versioned_docs/version-2.20/user-guide/plugins.md
Labels: approved, kind/documentation, release-note-none, lgtm

#456 fix: show correct last update time/author
  .github/workflows/node.js.yml
Labels: approved, release-note-none, lgtm

#455 docs: rewrite extension development documentation
  docs/developer-guide/annotations-form.md
  docs/developer-guide/plugin/api-reference/server/extension-client.md
  docs/developer-guide/plugin/api-reference/server/extension.md
  docs/developer-guide/plugin/basics/devtools.md
  docs/developer-guide/plugin/security/role-template.md
  versioned_docs/version-2.20/developer-guide/annotations-form.md
  versioned_docs/version-2.20/developer-guide/plugin/api-reference/server/extension-client.md
  versioned_docs/version-2.20/developer-guide/plugin/api-reference/server/extension.md
  versioned_docs/version-2.20/developer-guide/plugin/basics/devtools.md
  versioned_docs/version-2.20/developer-guide/plugin/security/role-template.md
Labels: approved, release-note-none, lgtm

#458 feat: diagrams can be rendered using Mermaid in a code block
  docusaurus.config.js
  package.json
  pnpm-lock.yaml
Labels: approved, release-note-none, lgtm

#459 docs: 增加阿里云云市场部署文档
  docs/getting-started/install/cloud/alibaba-cloud-market.md
  sidebars.js
  versioned_docs/version-2.20/getting-started/install/cloud/alibaba-cloud-market.md
  versioned_sidebars/version-2.20-sidebars.json
Labels: approved, do-not-merge/release-note-label-needed, lgtm

#428 chore: bump docusaurus to canary verison
  docusaurus.config.js
  package.json
  pnpm-lock.yaml
Labels: approved, release-note-none, lgtm
