Repository halo-dev/docs, pull requests merged in 2024-06, with the labels that each got.

#365 docs: add documentations for app store plugin
  docs/user-guide/app-store.md
  docs/user-guide/plugins.md
  docs/user-guide/themes.md
  sidebars.js
  static/img/user-guide/app-store/app-store-license-manage.png
  static/img/user-guide/app-store/app-store-license-status.png
  static/img/user-guide/app-store/app-store-page.png
  static/img/user-guide/app-store/app-store-pat.png
  static/img/user-guide/app-store/app-store-plugin-license.png
  static/img/user-guide/app-store/app-store-plugins.png
  static/img/user-guide/app-store/app-store-themes.png
  static/img/user-guide/app-store/app-store-upgrade-plugin.png
  static/img/user-guide/app-store/app-store-upgrade-theme.png
  versioned_docs/version-2.15/user-guide/app-store.md
  versioned_docs/version-2.15/user-guide/plugins.md
  versioned_docs/version-2.15/user-guide/themes.md
  versioned_sidebars/version-2.15-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#369 chore: bump pnpm version to 9
  .github/workflows/node.js.yml
  pnpm-lock.yaml
Labels: approved, release-note-none, lgtm, kind/improvement

#370 docs: update default docker registry
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/docker.md
  docs/getting-started/install/jar-file.md
  docs/getting-started/install/other/traefik.md
  docs/getting-started/install/podman.md
  docs/getting-started/install/slots/_docker-registry-list.md
  docs/user-guide/faq.md
  versioned_docs/version-2.16/getting-started/install/docker-compose.md
  versioned_docs/version-2.16/getting-started/install/docker.md
  versioned_docs/version-2.16/getting-started/install/jar-file.md
  versioned_docs/version-2.16/getting-started/install/other/traefik.md
  versioned_docs/version-2.16/getting-started/install/podman.md
  versioned_docs/version-2.16/getting-started/install/slots/_docker-registry-list.md
  versioned_docs/version-2.16/user-guide/faq.md
Labels: approved, release-note-none, lgtm

#371 docs: update pnpm version require
  docs/developer-guide/core/prepare.md
  versioned_docs/version-2.16/developer-guide/core/prepare.md
Labels: approved, kind/documentation, release-note-none, lgtm

#372 docs: remove tips related to mariadb driver
  docs/getting-started/install/slots/_docker-args.md
Labels: approved, kind/documentation, release-note-none, lgtm

#373 docs: add dynamic list doc
  docs/developer-guide/form-schema.md
Labels: approved, kind/documentation, release-note-none, lgtm

#375 docs: add detailed guide on how to use plugin settings
  docs/developer-guide/plugin/api-reference/server/setting-fetcher.md
  sidebars.js
Labels: approved, release-note-none, lgtm

#376 docs: add guide for customize and build controller
  docs/developer-guide/plugin/api-reference/server/reconciler.md
Labels: approved, release-note-none, lgtm
