Repository halo-dev/docs, pull requests merged in 2024-05, with the labels that each got.

#348 doc: add doc for template head processor extension point
  docs/developer-guide/plugin/api-reference/server/extension-points/template-head-processor.md
  sidebars.js
  versioned_docs/version-2.15/developer-guide/plugin/api-reference/server/extension-points/template-head-processor.md
  versioned_sidebars/version-2.15-sidebars.json
Labels: approved, release-note-none

#351 fix: api version for role template
  versioned_docs/version-2.12/developer-guide/plugin/api-reference/server/role-template.md
  versioned_docs/version-2.13/developer-guide/plugin/api-reference/server/role-template.md
  versioned_docs/version-2.14/developer-guide/plugin/api-reference/server/role-template.md
  versioned_docs/version-2.15/developer-guide/plugin/api-reference/server/role-template.md
Labels: approved, release-note-none, lgtm

#352 docs: remove colorScheme param for halo:comment tag
  docs/developer-guide/theme/template-tag.md
  versioned_docs/version-2.15/developer-guide/theme/template-tag.md
Labels: approved, kind/documentation, release-note-none, lgtm

#353 refactor: role template docs
  docs/developer-guide/plugin/api-reference/server/role-template.md
  versioned_docs/version-2.15/developer-guide/plugin/api-reference/server/role-template.md
Labels: approved, release-note-none, lgtm

#354 docs: tencent cloud lighthouse
  docs/getting-started/install/cloud/tencent-cloud-lighthouse.md
  sidebars.js
  static/img/install/tencent-cloud-lighthouse/1panel-info.png
  static/img/install/tencent-cloud-lighthouse/1panel-login.png
  static/img/install/tencent-cloud-lighthouse/1panel-overview.png
  static/img/install/tencent-cloud-lighthouse/application.png
  static/img/install/tencent-cloud-lighthouse/buy.png
  static/img/install/tencent-cloud-lighthouse/domain.png
  static/img/install/tencent-cloud-lighthouse/firewall.png
  static/img/install/tencent-cloud-lighthouse/halo-setup.png
  static/img/install/tencent-cloud-lighthouse/installed-apps.png
  static/img/install/tencent-cloud-lighthouse/upgrade.png
  static/img/install/tencent-cloud-lighthouse/websites.png
  versioned_docs/version-2.15/getting-started/install/cloud/tencent-cloud-lighthouse.md
  versioned_sidebars/version-2.15-sidebars.json
Labels: approved, kind/documentation, release-note-none, lgtm

#350 feat: modify ui service startup way
  docs/developer-guide/core/run.md
Labels: approved, lgtm, release-note

#356 docs: add a description regarding external-url
  docs/getting-started/install/cloud/tencent-cloud-lighthouse.md
  static/img/install/tencent-cloud-lighthouse/external-url.png
  versioned_docs/version-2.15/getting-started/install/cloud/tencent-cloud-lighthouse.md
Labels: approved, kind/documentation, release-note-none, lgtm

#357 chore: use selfhosted-meilisearch as docs search engine
  docusaurus.config.js
  package.json
  pnpm-lock.yaml
  src/theme/SearchBar.js
Labels: approved, release-note-none, lgtm, kind/improvement

#358 chore: use esbuild instead of babel
  docusaurus.config.js
  package.json
  pnpm-lock.yaml
Labels: approved, release-note-none, lgtm, kind/improvement

#359 chore: use swc instead of esbuild
  docusaurus.config.js
  package.json
  pnpm-lock.yaml
Labels: kind/bug, approved, release-note-none, lgtm

#361 docs: update document of plugin example
  docs/developer-guide/plugin/examples/todolist.md
Labels: approved, release-note-none, lgtm

#363 fix: total pages in archives.html sample
  docs/developer-guide/theme/template-variables/archives.md
  versioned_docs/version-2.15/developer-guide/theme/template-variables/archives.md
Labels: approved, release-note-none, lgtm

#364 typo: 登陆 -> 登录
  docs/developer-guide/plugin/api-reference/server/extension-points/additional-webfilter.md
  docs/developer-guide/plugin/api-reference/server/role-template.md
  docs/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.10/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.11/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.12/developer-guide/plugin/api-reference/server/extension-points/additional-webfilter.md
  versioned_docs/version-2.12/developer-guide/plugin/api-reference/server/role-template.md
  versioned_docs/version-2.12/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.13/developer-guide/plugin/api-reference/server/extension-points/additional-webfilter.md
  versioned_docs/version-2.13/developer-guide/plugin/api-reference/server/role-template.md
  versioned_docs/version-2.13/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.14/developer-guide/plugin/api-reference/server/extension-points/additional-webfilter.md
  versioned_docs/version-2.14/developer-guide/plugin/api-reference/server/role-template.md
  versioned_docs/version-2.14/getting-started/install/other/nginxproxymanager.md
  versioned_docs/version-2.15/developer-guide/plugin/api-reference/server/extension-points/additional-webfilter.md
  versioned_docs/version-2.15/developer-guide/plugin/api-reference/server/role-template.md
  versioned_docs/version-2.15/getting-started/install/other/nginxproxymanager.md
Labels: approved, kind/documentation, release-note-none, lgtm

#366 fix: broken links
  docs/developer-guide/plugin/basics/ui/entry.md
  versioned_docs/version-2.12/developer-guide/plugin/basics/ui/entry.md
  versioned_docs/version-2.13/developer-guide/plugin/basics/ui/entry.md
  versioned_docs/version-2.14/developer-guide/plugin/basics/ui/entry.md
  versioned_docs/version-2.15/developer-guide/plugin/basics/ui/entry.md
Labels: approved, release-note-none, lgtm
