Repository halo-dev/docs, pull requests merged in 2024-08, with the labels that each got.

#392 chore: update afdian url
  docs/contribution/sponsor.md
  docs/intro.md
  versioned_docs/version-2.10/contribution/sponsor.md
  versioned_docs/version-2.10/intro.md
  versioned_docs/version-2.11/contribution/sponsor.md
  versioned_docs/version-2.11/intro.md
  versioned_docs/version-2.12/contribution/sponsor.md
  versioned_docs/version-2.12/intro.md
  versioned_docs/version-2.13/contribution/sponsor.md
  versioned_docs/version-2.13/intro.md
  versioned_docs/version-2.14/contribution/sponsor.md
  versioned_docs/version-2.14/intro.md
  versioned_docs/version-2.15/contribution/sponsor.md
  versioned_docs/version-2.15/intro.md
  versioned_docs/version-2.16/contribution/sponsor.md
  versioned_docs/version-2.16/intro.md
  versioned_docs/version-2.17/contribution/sponsor.md
  versioned_docs/version-2.17/intro.md
  versioned_docs/version-2.18/contribution/sponsor.md
  versioned_docs/version-2.18/intro.md
Labels: approved, release-note-none, lgtm, kind/cleanup

#391 docs: refine docs for postFinder.listByOwner
  docs/developer-guide/theme/finder-apis/post.md
  versioned_docs/version-2.18/developer-guide/theme/finder-apis/post.md
Labels: approved, release-note-none, lgtm

#393 docs: make comment and reply list item operations extendable
  docs/developer-guide/plugin/api-reference/ui/extension-points/comment-list-item-operation-create.md
  docs/developer-guide/plugin/api-reference/ui/extension-points/interface/ListedComment.md
  docs/developer-guide/plugin/api-reference/ui/extension-points/interface/ListedReply.md
  docs/developer-guide/plugin/api-reference/ui/extension-points/reply-list-item-operation-create.md
  sidebars.js
  static/img/developer-guide/plugin/api-reference/ui/extension-points/comment-list-item-operation-create.png
  static/img/developer-guide/plugin/api-reference/ui/extension-points/reply-list-item-operation-create.png
  versioned_docs/version-2.18/developer-guide/theme/finder-apis/post.md
Labels: approved, release-note-none, lgtm

#396 docs: improve the display of docker-compose examples
  docs/getting-started/install/docker-compose.md
  docs/getting-started/install/slots/_docker-args.md
  i18n/zh-Hans/code.json
  versioned_docs/version-2.18/getting-started/install/docker-compose.md
  versioned_docs/version-2.18/getting-started/install/slots/_docker-args.md
Labels: approved, kind/documentation, release-note-none, lgtm

#399 Rectify the invalid external URL
  docs/getting-started/install/docker-compose.md
  versioned_docs/version-2.18/getting-started/install/docker-compose.md
Labels: approved, lgtm, release-note

#400 docs: add formkit select component
  docs/developer-guide/form-schema.md
Labels: approved, release-note-none, lgtm

#403 docs: update work directory documentation
  docs/getting-started/prepare.md
  versioned_docs/version-2.18/getting-started/prepare.md
Labels: approved, release-note-none, lgtm

#404 docs: update select field selector document
  docs/developer-guide/form-schema.md
Labels: approved, release-note-none, lgtm

#406 docs: update backup documentation
  docs/user-guide/backup.md
  static/img/user-guide/backup/restore-complete.png
  static/img/user-guide/backup/restore-upload.png
  static/img/user-guide/backup/restore.png
  static/img/user-guide/backup/waiting-restart.png
Labels: approved, kind/documentation, release-note-none, lgtm
