Repository halo-dev/docs, pull requests merged in 2024-04, with the labels that each got.

#335 chore: update workflow
  .github/workflows/node.js.yml
Labels: approved, release-note-none, lgtm

#337 docs: update prepare document
  docs/getting-started/prepare.md
  versioned_docs/version-2.14/getting-started/prepare.md
Labels: approved, kind/documentation, release-note-none, lgtm

#338 docs: update example of theme manifest file
  docs/developer-guide/theme/config.md
  docs/developer-guide/theme/prepare.md
  docs/developer-guide/theme/settings.md
  versioned_docs/version-2.14/developer-guide/theme/config.md
  versioned_docs/version-2.14/developer-guide/theme/prepare.md
  versioned_docs/version-2.14/developer-guide/theme/settings.md
Labels: approved, release-note-none, lgtm

#339 docs: update example of plugin manifest file
  docs/developer-guide/plugin/basics/manifest.md
  docs/developer-guide/plugin/examples/todolist.md
  versioned_docs/version-2.14/developer-guide/plugin/basics/manifest.md
  versioned_docs/version-2.14/developer-guide/plugin/examples/todolist.md
Labels: approved, release-note-none, lgtm

#340 docs: add documentation for user tab
  docs/developer-guide/plugin/api-reference/ui/extension-points/uc-user-profile-tabs-create.md
  docs/developer-guide/plugin/api-reference/ui/extension-points/user-detail-tabs-create.md
  sidebars.js
  static/img/developer-guide/plugin/api-reference/ui/extension-points/uc-user-profile-tabs-create.png
  static/img/developer-guide/plugin/api-reference/ui/extension-points/user-detail-tabs-create.png
Labels: approved, kind/documentation, release-note-none, lgtm

#341 Add documentation for websocket
  docs/developer-guide/plugin/api-reference/server/websocket.md
  sidebars.js
Labels: approved, release-note-none, lgtm

#343 Fix typo condtions to conditions
  docs/developer-guide/plugin/api-reference/server/reconciler.md
  versioned_docs/version-2.12/developer-guide/plugin/api-reference/server/reconciler.md
  versioned_docs/version-2.13/developer-guide/plugin/api-reference/server/reconciler.md
  versioned_docs/version-2.14/developer-guide/plugin/api-reference/server/reconciler.md
Labels: approved, do-not-merge/release-note-label-needed, lgtm

#342 docs: add issues field for theme and plugin manifest example
  docs/developer-guide/plugin/basics/manifest.md
  docs/developer-guide/plugin/examples/todolist.md
  docs/developer-guide/theme/config.md
  docs/developer-guide/theme/prepare.md
  docs/developer-guide/theme/settings.md
Labels: approved, kind/documentation, release-note-none, lgtm

#344 docs: update r2dbc url for MariaDB
  docs/getting-started/install/slots/docker-args.md
  versioned_docs/version-2.14/getting-started/install/slots/docker-args.md
Labels: do-not-merge/release-note-label-needed
