Repository halo-dev/docs, pull requests merged in 2024-03, with the labels that each got.

#320 Add documentation for authentication webfilter extension points
  docs/developer-guide/plugin/api-reference/server/extension-points/authentication-webfilter.md
  docs/developer-guide/plugin/api-reference/server/extension-points/index.md
  sidebars.js
Labels: approved, release-note-none, lgtm

#322 doc: refine doc for route rules of custom extension apis
  docs/developer-guide/plugin/api-reference/server/extension.md
Labels: approved, release-note-none, lgtm

#330 addressing outdated version issue of Checkstyle in code style documentation
  docs/developer-guide/core/code-style.md
Labels: approved, release-note-none, lgtm

#324 docs: update sample of docker compose file
  docs/getting-started/install/docker-compose.md
  versioned_docs/version-2.13/getting-started/install/docker-compose.md
Labels: approved, kind/documentation, release-note-none

#325 docs: add title prop for editor create extension point
  docs/developer-guide/plugin/api-reference/ui/extension-points/editor-create.md
Labels: approved, kind/documentation, release-note-none, lgtm

#327 docs: add formkit verfiyForm documentation
  docs/developer-guide/form-schema.md
  static/img/formkit/formkit-verify-form.png
Labels: approved, kind/documentation, release-note-none, lgtm

#332 docs: add the selection attribute to handleDrop
  docs/developer-guide/plugin/api-reference/ui/extension-points/default-editor-extension-create.md
Labels: approved, kind/documentation, release-note-none, lgtm

#333 docs: delete unnecessary options
  versioned_docs/version-2.13/getting-started/install/docker.md
  versioned_docs/version-2.13/getting-started/install/podman.md
  versioned_docs/version-2.13/intro.md
Labels: approved, release-note-none, lgtm
