Repository halo-dev/docs, pull requests merged in 2025-05, with the labels that each got.

#494 chore: add rybbit tracking script
  docusaurus.config.js
Labels: approved, release-note-none

#495 chore: remove umami tracking script
  docusaurus.config.js
Labels: approved, release-note-none

#496 docs: add Rainbond button
  sidebars.js
  versioned_sidebars/version-2.20-sidebars.json
Labels: release-note-none, lgtm

#498 chore: bump docusaurus to 3.8
  .github/workflows/node.js.yml
  docusaurus.config.js
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: approved, release-note-none, lgtm

#497 docs: update document for UserLoginEvent and UserLogoutEvent
  docs/developer-guide/plugin/interaction/shared-events.md
Labels: approved, lgtm, release-note
